version: 2

jobs:
  build:
    docker:
      - image: kudo/ubuntu-nonroot:18.04
        user: ubuntu
        environment:
          DEBIAN_FRONTEND: noninteractive
          TZ: UTC
          DISABLE_JIT: true

    working_directory: ~/v8-android-buildscripts
    steps:
      - run:
          name: Setup Ubuntu environment
          command: |
            sudo ln -fs /usr/share/zoneinfo/UTC /etc/localtime
            sudo apt-get update
            sudo apt-get upgrade -y
            sudo apt-get install -y apt-utils sudo lsb-core git python nodejs npm wget

      - checkout

      - run:
          name: Export settings from npm package
          command: |
            npm run export_npm_env

      - run:
          name: Setup V8 build environment
          command: |
            scripts/setup.sh -r ${V8_VERSION} android

      - run:
          name: Patch V8
          command: |
            scripts/patch.sh android

      - run:
          name: Build V8
          command: |
            scripts/build.sh android
            scripts/archive.sh android

      - run:
          name: Build V8 No Intl
          command: |
            NO_INTL=1 scripts/build.sh android
            NO_INTL=1 scripts/archive.sh android

      - run:
          name: Archive
          command: |
            tar cvfz dist.tgz dist

      - store_artifacts:
          path: dist.tgz

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
