version: 2

jobs:
  build:
    docker:
      - image: kudo/ubuntu-nonroot:18.04
        user: ubuntu
        environment:
          DEBIAN_FRONTEND: noninteractive
          TZ: UTC

    working_directory: ~/v8-android-buildscripts
    steps:
      - run:
          name: Setup Ubuntu environment
          command: |
            sudo ln -fs /usr/share/zoneinfo/UTC /etc/localtime
            sudo apt-get update
            sudo apt-get upgrade -y
            sudo apt-get install -y apt-utils sudo lsb-core git python nodejs npm

      - checkout

      - run:
          name: Export settings from npm package
          command: |
            npm run export_npm_env

      - run:
          name: Setup V8 build environment
          command: |
            scripts/setup.sh -s -r ${V8_VERSION}

      - run:
          name: Patch V8
          command: |
            scripts/patch.sh

      - run:
          name: Build V8
          command: |
            scripts/build.sh

      - run:
          name: Archive
          command: |
            scripts/archive.sh
            tar cvfz dist.tgz dist

      - store_artifacts:
          path: dist.tgz

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
